<?php

use App\Forms;
use Illuminate\Database\Seeder;

class FormsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Forms::insert([
                [
                    'id' => 1,
                    'name' => 'create_movie',
                    'field' => 'name',
                    'label' => 'Title',
                    'required' => 1,
                    'type' => 'text',
                    'order' => 10,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],
                [
                    'id' => 2,
                    'name' => 'create_movie',
                    'field' => 'sort_name',
                    'label' => 'Sort Name',
                    'required' => 0,
                    'type' => 'text',
                    'order' => 20,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 3,
                    'name' => 'create_movie',
                    'field' => 'bio',
                    'label' => 'Description',
                    'required' => 1,
                    'type' => 'textarea',
                    'order' => 30,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 4,
                    'name' => 'create_movie',
                    'field' => 'purchased',
                    'label' => 'Purchased',
                    'required' => 0,
                    'type' => 'date',
                    'order' => 40,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 5,
                    'name' => 'create_movie',
                    'field' => 'rating',
                    'label' => 'Rating',
                    'required' => 1,
                    'type' => 'range',
                    'order' => 50,
                    'range_from' => 1,
                    'range_to' => 10,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 6,
                    'name' => 'create_movie',
                    'field' => 'released',
                    'label' => 'Released',
                    'required' => 1,
                    'type' => 'range',
                    'order' => 60,
                    'range_from' => 1920,
                    'range_to' => 9999,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 7,
                    'name' => 'create_movie',
                    'field' => 'running_time',
                    'label' => 'Running Time',
                    'required' => 1,
                    'type' => 'text',
                    'order' => 70,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 8,
                    'name' => 'create_movie',
                    'field' => 'certificate_id',
                    'label' => 'Certificate',
                    'required' => 1,
                    'type' => 'select',
                    'order' => 80,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => 'certificates',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 9,
                    'name' => 'create_movie',
                    'field' => 'format_id',
                    'label' => 'Format',
                    'required' => 1,
                    'type' => 'select',
                    'order' => 90,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => 'formats',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 10,
                    'name' => 'create_movie',
                    'field' => 'studio_id',
                    'label' => 'Studio',
                    'required' => 0,
                    'type' => 'select',
                    'order' => 100,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => 'studios',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 11,
                    'name' => 'create_movie',
                    'field' => 'imdb_id',
                    'label' => 'IMDb',
                    'required' => 0,
                    'type' => 'text',
                    'order' => 110,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 12,
                    'name' => 'create_movie',
                    'field' => 'image',
                    'label' => 'Image Path',
                    'required' => 0,
                    'type' => 'text',
                    'order' => 120,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 13,
                    'name' => 'create_movie',
                    'field' => 'image_upload',
                    'label' => 'Upload Image',
                    'required' => 0,
                    'type' => 'file',
                    'order' => 130,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => 'movie-poster',
                    'class' => '',
                ],

                [
                    'id' => 14,
                    'name' => 'create_person',
                    'field' => 'forename',
                    'label' => 'Name',
                    'required' => 1,
                    'type' => 'text',
                    'order' => 10,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 15,
                    'name' => 'create_person',
                    'field' => 'surname',
                    'label' => 'Surname',
                    'required' => 0,
                    'type' => 'text',
                    'order' => 20,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 16,
                    'name' => 'create_person',
                    'field' => 'birthday',
                    'label' => 'Born',
                    'required' => 0,
                    'type' => 'date',
                    'order' => 30,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 17,
                    'name' => 'create_person',
                    'field' => 'deceased',
                    'label' => 'Died',
                    'required' => 0,
                    'type' => 'date',
                    'order' => 40,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 18,
                    'name' => 'create_person',
                    'field' => 'bio',
                    'label' => 'Bio',
                    'required' => 0,
                    'type' => 'textarea',
                    'order' => 50,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 19,
                    'name' => 'create_person',
                    'field' => 'imdb_id',
                    'label' => 'IMDb',
                    'required' => 0,
                    'type' => 'text',
                    'order' => 60,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],

                [
                    'id' => 20,
                    'name' => 'create_person',
                    'field' => 'image',
                    'label' => 'Image Path',
                    'required' => 0,
                    'type' => 'text',
                    'order' => 70,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => '',
                    'class' => '',
                ],
                [
                    'id' => 21,
                    'name' => 'create_person',
                    'field' => 'image_upload',
                    'label' => 'Upload Image',
                    'required' => 0,
                    'type' => 'file',
                    'order' => 80,
                    'range_from' => 0,
                    'range_to' => 0,
                    'options' => '',
                    'default' => 'person-poster',
                    'class' => '',
                ]
        ]);
    }
}
